name: commit

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      channel: canary

  hello_world:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: hello world
        run: echo hello world
