name: pull_request_labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  opened:
    runs-on: ubuntu-latest
    if: github.event_name == "pull_request" && github.pull_request.action == "opened"
    concurrency: pr-labels-{{ github.pull_request.number }}
    steps:
      - name: Label opened pull requests with triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --add-labels "triage"

  label:
    runs-on: ubuntu-latest
    if: github.event_name == "pull_request" && github.pull_request.action != "opened"
    concurrency: pr-labels-{{ github.pull_request.number }}
    steps:
      - name: Require labels
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
        run: |
          if ($null -eq $env:GITHUB_PR_LABELS) {
            throw "Missing required labels"
          }

          $labels = $env:GITHUB_PR_LABELS.Split(',')
          if ($labels.Contains("triage")) {
            gh pr edit --remove-labels "triage"
            $labels = $labels | Where-Object { $_ -ne "triage" }
          }

          if ($labels.Length -eq 0) {
            throw "Pull request must have at least one label (excluding triage)"
          }
