name: pull_request_labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Require labels
        shell: pwsh
        env:
          GITHUB_PR_LABELS: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          GITHUB_PR: ${{ toJSON(github.event.pull_request) }}
        run: |
          $env:GITHUB_PR_LABELS.GetType()
          $env:GITHUB_PR_LABELS
          $env:GITHUB_PR

          if ([string]::IsNullOrEmpty($env:GITHUB_PR_LABELS)) {
            throw "No labels found."
          }