name: pull_request_labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    concurrency: ci-labels-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Require labels
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $labelCount = [int](gh pr view --json labels --jq ".labels | length")

          if ($labelCount -eq 0) {
            throw "No labels found."
          }
