name: release

on:
  push:
    branches:
      - main
      - release/v*
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest
    concurrency: ci-create-release-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create the release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $channel, $isPrerelease = .\scripts\Get-Channel.ps1
          $currentRelease = .\scripts\Get-CurrentWhimRelease.ps1 -Channel $channel
          $currentRelease = "v${currentRelease}"

          $nextRelease = .\scripts\Get-NextWhimRelease.ps1 -Channel $channel
          $nextRelease = "v${nextRelease}"

          $resp = gh api repos/$env:GITHUB_REPOSITORY/releases/generate-notes `
            -H "Accept: application/vnd.github.v3+json" `
            -f tag_name=$nextRelease `
            -f previous_tag_name=$currentRelease `
            | ConvertFrom-Json

          $notes = $resp.body ?? "Initial release"

          gh release create "$nextRelease" `
            --title "$nextRelease" `
            --prerelease="$isPrerelease" `
            --notes $notes

  release:
    runs-on: windows-latest
    concurrency: ci-release-${{ github.ref }}
    needs:
      - create-release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # TODO: Build

      - name: Upload release assets
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $channel, $isPrerelease = .\scripts\Get-Channel.ps1
          $currentRelease = .\scripts\Get-CurrentWhimRelease.ps1 -Channel $channel
          $currentRelease = "v${currentRelease}"

          gh release upload "$currentRelease" bin/whim-install.exe
