name: release

on:
  push:
    branches:
      # Canary
      - main

      # Beta
      - release/v*
    tags:
      # Stable
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine channel
        shell: pwsh
        # The channel must be either canary, beta, or stable.
        # Canary releases must be on the `main` branch.
        # Beta and stable releases must be on a `release/*` branch.
        run: |
          $channel = $null
          $isPrerelease = $true

          if ($env:GITHUB_REF -eq "refs/heads/main") {
            $channel = "canary"
          } elseif ($env:GITHUB_REF.StartsWith("refs/heads/release/")) {
            $channel = "beta"
          } elseif ($env:GITHUB_REF.StartsWith("refs/tags/v")) {
            $channel = "stable"
            $isPrerelease = $false
          } else {
            throw "Invalid branch or tag name."
          }

          $isPrerelease = $isPrerelease.ToString().ToLower()
          "channel=${channel}" >> $env:GITHUB_ENV
          "isPrerelease=${isPrerelease}" >> $env:GITHUB_ENV

      - name: Get the release version
        id: vars
        shell: pwsh
        run: |
          $result = git describe --match v*
          $build = 0
          $version = ""
          $commit = $env:GITHUB_SHA.Substring(0, 7)

          # If result doesn't contain any hyphens, then the current commit is tagged.
          if ($result -eq $null) {
            throw "Could not find a tag."
          } elseif ($result.Contains("-") -eq $false) {
            $build = 0
            $version = $result
          } else {
            # Split the version and build number.
            $parts = $result.Split("-")

            $version = $parts[0]
            $version = $version.Substring(1)

            $build = $parts[1]
          }

          # Write the release to the environment in the format version.build-channel
          $release = "v" + $version + "." + $build + "-" + $env:channel + "." + $commit
          "release=${release}" >> $env:GITHUB_ENV

      - name: Determine the release tag
        shell: pwsh
        run: |
          if ($env:channel -eq "canary") {
            $tag = "canary"
          } elseif ($env:channel -eq "beta") {
            $tag = "beta"
          } elseif ($env:channel -eq "stable") {
            $tag = $env:release
          } else {
            throw "Invalid channel."
          }

          "tag=${tag}" >> $env:GITHUB_ENV

      - name: Print out the variables
        shell: pwsh
        run: |
          Write-Output "Channel: ${env:channel}"
          Write-Output "Is prerelease: ${env:isPrerelease}"
          Write-Output "Release: ${env:release}"
          Write-Output "Tag: ${env:tag}"

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ env.isPrerelease }}
          title: "Release ${{ env.release }}"
          automatic_release_tag: ${{ env.tag }}
          files: |
            bin/whim-install.exe
            CHANGELOG.md
